Add files via upload
tilburgsciencehub/website pull request #1118
Opened 2024-03-11 15:04 UTC by arutyunovv

Dear @lachlandeer,

This is (a draft of) my article for the building block on RDDs with discrete running variables. It includes an explanation of why such RDDs differ from ones with a continuous assignment variable, three approaches that can be used for causal inference in such designs, a brief example in R, and a summary. 

Please let me know which changes you think I should make; in the meantime, I will be reviewing it myself to see what can be improved. Thanks!

Best, 
Victor

2024-03-21 20:09 UTC, lachlandeer commented
@srosh2000 

Can you read this over and provide some suggestions to enhance?

Thanks!

L

2024-04-05 15:24 UTC, srosh2000 commented
@arutyunovv General remark on the file location. Make sure to add this .md file under `content/topics/Analyze/causal-inference/rdd` Then when you use hugo to preview the building block it should appear in the RDD section. 

I'm yet to fully go through the building block. Will finalise my comments very soon :)

2024-04-05 16:16 UTC, srosh2000 requested changes
I am thinking it might be good to maybe break this down into a theory building block and another which solely focuses on implementation and associated challenges. What are your thoughts on this @lachlandeer ?

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +The advantage of the local randomisation design when the running variable is discrete is that it does not rely on assumptions about the continuity of the regression functions on either side of the cu
Not sure if the previous BB explain the CEF. Good to define it beforehand.

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +In cases where the local randomisation approach cannot be applied because of the restrictions it places on bandwidth size, we can use an amended version of the continuity-based approach described by
Hyperlink the paper you refer to here

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +The advantage of the local randomisation design when the running variable is discrete is that it does not rely on assumptions about the continuity of the regression functions on either side of the cu
Also add a subtitle Advantages of this approach or something alike for better structuring

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +
Break it down into sub heading: Solutions to this issue and enlist the two approaches.

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +
Add subheading stating the issue you talk about below

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +In the past, researchers used to cluster standard errors by the value of the running variable in order to circumvent this issue, following Lee and Card (2008). However, Kolesár and Rothe (2018) show,
Hyperlink the paper

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +
Add sub-heading: Implementation challenges with BSD or something like that

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +In this section, I demonstrate a simple implementation of BSD confidence intervals in R using the [RDHonest](https://github.com/kolesarm/RDHonest/blob/master/doc/RDHonest.pdf) package. The package in
hyperlink the study

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +RDScatter(log(earnings) ~ yearat14, data = cghs, cutoff = 1947, avg = Inf, xlab = "Year aged 14", ylab = "Log earnings", propdotsize = TRUE)
include screenshots of the output to give the reader an idea of how it would look like

2024-04-05 16:16 UTC, srosh2000 commented on RDD with Discrete Running Variables.md
> +## Summary
Turn it into a summary box and keep it short and simple bullet points.

2024-04-29 10:19 UTC, lachlandeer commented
hey @arutyunovv 

have you integrated the suggested changes from @srosh2000?

2024-04-29 10:45 UTC, arutyunovv commented
Hi @lachlandeer, 

I haven't integrated all of the changes yet, but should finish doing so within the next 2-3 days. I'll let you know as soon as I am done.

2024-05-21 16:13 UTC, closed without merging