First draft of staggered DiD BB
tilburgsciencehub/website pull request #867
Opened 2023-09-19 11:53 UTC by srosh2000

Here's a first draft! I have put it under regressions section as a placeholder till we figure out the positioning of the causal inference content. Looking forward to your feedback! :)

2023-09-19 12:53 UTC, shrabasteebanerjee requested changes
added my comments!

2023-09-19 12:53 UTC, shrabasteebanerjee commented on content/building-blocks/analyze-data/regressions/staggered-did.md
> +
cite your other building block here?

2023-09-19 12:53 UTC, shrabasteebanerjee commented on content/building-blocks/analyze-data/regressions/staggered-did.md
> +
mention that "additional resources/see also" section contains more details

2023-09-19 12:53 UTC, shrabasteebanerjee commented on content/building-blocks/analyze-data/regressions/staggered-did.md
> +
mention that using amazon as the control group means that we assume no spillovers between the 2, and no time varying differences. might to good to add this as a tip or note, with the general lesson that the considerations for choice of control group still remain the same regardless of staggered vs regular DiD

2023-09-19 12:53 UTC, shrabasteebanerjee commented on content/building-blocks/analyze-data/regressions/staggered-did.md
> +
you introduce the setup by saying we'll use amazon as control, so the not-yet-treated comes as a bit of a surprise. clarify upfront that we will use 2 different control groups, and then go through them one by one

2023-09-19 12:53 UTC, shrabasteebanerjee commented on content/building-blocks/analyze-data/regressions/staggered-did.md
> +
perhaps prettify the tables using modelsummary, etable or similar?

2023-09-19 12:53 UTC, shrabasteebanerjee commented on content/building-blocks/analyze-data/regressions/staggered-did.md
> +
do you also want to add never treated results, given you talk about the method?

2023-09-29 15:34 UTC, hannesdatta commented
@srosh2000 - could you please take a look at @shrabasteebanerjee comments and implement them when you find the time? note also i rewrote the beginning a bit - it was very wordy. Try to shorten/be concise in your writing.

2023-09-30 10:19 UTC, srosh2000 commented
@hannesdatta Noted! Yes it's on my to do list. Will finalise it this coming week

2023-10-18 10:21 UTC, closed without merging

2023-10-18 10:22 UTC, srosh2000 commented
Made a new PR incorporating the changes. Made a new PR as I had to relocate this file. Closing this PR for now,